name: lint

on:
  pull_request:
    branches: [master, main]

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run lint:ls
      - run: npm run lint:md
